name: loyalty_program
description: A pure Dart collection of global airline, hotel, and car rental loyalty programs, status tiers, and milestone requirements.
version: 1.0.0-beta.1
repository: https://github.com/inspiretechdevs/loyalty_program

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
